version: '3'
services: 
    app:
        build:
            dockerfile: Dockerfile.dev
            context: ./client/app
        expose: 
            - "19000"
            - "19001"
            - "19002"
        ports: 
            - "3000:3000"
            - "19000:19000"
            - "19001:19001"
            - "19002:19002"
            - "19006:19006"
        stdin_open: true
        volumes: 
            - /app/node_modules
            - ./client/app:/app
    server:
        build:
            dockerfile: Dockerfile.dev
            context: ./server
        ports: 
            - "5000:5000"
        stdin_open: true
        volumes: 
            - /app/node_modules
            - ./server:/app
             