FROM node:alpine



WORKDIR '/app'

COPY ./package.json ./

RUN  npm install
RUN apk add --no-cache bash git \
  && npm install --global --unsafe-perm express \
  && npm cache clean --force

COPY . . 
CMD ["npm","run","dev"]